# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kizashi < Formula
  desc "Streama e visualiza logs locais estruturados no terminal"
  homepage "https://github.com/Morpa/kizashi"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Morpa/kizashi/releases/download/v1.0.0/kizashi_1.0.0_darwin_amd64.tar.gz"
      sha256 "addd6be34091a54a0bd93967488057a6c26bac2e5491958a3052eb73282d5830"

      define_method(:install) do
        bin.install "kizashi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Morpa/kizashi/releases/download/v1.0.0/kizashi_1.0.0_darwin_arm64.tar.gz"
      sha256 "fc6a162990a5d805ebe5d4d642dd4f63581183f5526e0f74a7fffc37e054c00a"

      define_method(:install) do
        bin.install "kizashi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Morpa/kizashi/releases/download/v1.0.0/kizashi_1.0.0_linux_amd64.tar.gz"
      sha256 "6c21fbb7eaad0c367cd2225ad88715bfb9d1c9f097fcba5ed59afb6854c0450f"
      define_method(:install) do
        bin.install "kizashi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Morpa/kizashi/releases/download/v1.0.0/kizashi_1.0.0_linux_arm64.tar.gz"
      sha256 "93b757057f7452a70b48d3c1ab44094de6e4dbf9d240dfd8316ceec48d7e0518"
      define_method(:install) do
        bin.install "kizashi"
      end
    end
  end
end
