# This file was generated by GoReleaser. DO NOT EDIT.
cask "kizashi" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "6113aa2f4e57fb7e27d7c182b1c55c0aab22c1eba523f7ee30916bf734905308"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "888f1e233b903d663199c5123e61c7bc670435c48a2ceb21b2222014691e9d74"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "84fc9d671b6fd1ddd044136bca69cb59b16d89727103d712ccdc3a1aa48438e0"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ff779cb7827c5d9953fba7d9f0faa63e0f4113e069e2543437a788ceb6c18c4"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kizashi"
  desc "Streama e visualiza logs locais estruturados no terminal"
  homepage "https://github.com/Morpa/kizashi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kizashi"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kizashi"]
    end
  end

  # No zap stanza required

end
