# This file was generated by GoReleaser. DO NOT EDIT.
cask "kizashi" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "175612ff889ccd41bbdbbcb02b30af3017734604e6bb5b4acb8f8bba58877f82"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "20445ab61e22c674b22944ee3622b4424674c178896b0e785396cbcdc711949f"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76b4f54fe0b4f49ff5cc76ad40387ce40b10c5491e2526431eda4ac87d96b582"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8585f7fcb61c21806ee40a148723b485575c10191779d8f87320d5a7633834af"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kizashi"
  desc "Streama e visualiza logs locais estruturados no terminal"
  homepage "https://github.com/Morpa/kizashi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kizashi"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kizashi"]
    end
  end

  # No zap stanza required

end
