# This file was generated by GoReleaser. DO NOT EDIT.
cask "kizashi" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "a1c3017f735530bcce6fa007f785d8563f5d83eb5475445740fce5d982b9175f"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be6e1e522ea46b14305dc5e15be80430d403d1d658f31635094f7643f0b1defe"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77f1202a946c1146eaf00d9758cded372a3349c8cdab2f2f0a952b434c604978"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f9a4872755ef38fd5ca09721df2cb7c9e0eef527b96e6c09be3fd6a2424804a"
      url "https://github.com/Morpa/kizashi/releases/download/v#{version}/kizashi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kizashi"
  desc "Streama e visualiza logs locais estruturados no terminal"
  homepage "https://github.com/Morpa/kizashi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kizashi"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kizashi"]
    end
  end

  # No zap stanza required

end
